#include <string.h>
#include <ctype.h>
#include <tuple>
#include <vector>
#include <string>
#include <iostream>
#include <map>
#include <fstream>
#include <sstream>
#include <functional>
#include <stdexcept>
#include <set>
